project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "Trevor Miller ePortfolio"
  navbar:
    right:
    - text: Home 
      href: index.qmd 
    - text: Projects 
      href: projects.qmd 
    - text: Resume 
      href: resume.qmd
      
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css

editor: visual

